### ISSUE TITLE
Ore Wash Plant not working in Chemical Bath mode

### ISSUE THREAD

**Issue by Highbeam** [draknyte1/GTplusplus#330]
# Issue Title  
Ore Wash Plant not working in Chemical Bath mode

## Expected Behavior
As discussed briefly with Alk - I have set up the Ore Wash Plant in Chemical Bath mode but I can't get it working.

## Current Behavior
I've encountered multiple bugs:
1) When the Ore Wash Plant is formed in Ore Washer mode, the input hatches won't accept Mercury.  To fix this, I had to break the controller and input hatch, place the controller and set mode to chemical bath FIRST, then place the input hatch so the multiblock forms.
2) Once the multiblock was formed, I fixed all maintenance issues, powered it and put some crushed nickel ore in.  But nothing happens.

## Game Environment
GTNH Epsilon - 2.0.4.6

Has anyone got this to work?  If so, what did you do?

**Comment by Highbeam** [comment]
worth noting we're still on 2.0.4.6 so I'm not sure if it is anything to do with the same issue where Centrifuge recipes don't start

**Comment by draknyte1** [comment]
Was either fixed by https://github.com/draknyte1/GTplusplus/commit/63b22ce1036b45f5da4882518f39a0762d0d6f69 or https://github.com/draknyte1/GTplusplus/commit/0fbf214b5a95c7f4cf5dab6d4c393feb4fb80758.

**Comment by Highbeam** [comment]
In version 2.0.5.1 this isn't working.

I have tried switching modes and running it.

I have tried to fill the ore washer with water, place the controller and switch mode before placing the final piece to form and it still won't run.

Any suggestions?

**Comment by Lithorn** [comment]
2.0.5.1, Prospercraft server. Same issue, Chem bath mode non functional, attempted several but was really after Zirconium

**Comment by Hydrant777** [comment]
I know this is quite old thread but I made the Ore Washing Plant working in Chemical Bath mode by supplying it with water just like in the default mode. It does not require water afterwards, it just has to be filled up with it.
Hope this helps.
EDIT: Modpack: InfiTech 2u Fear the Night
